# : Manager [[[

[manager]
cwd = { fg = "#eae1d4" }

# Tab
tab_active = { fg = "#3d2f00", bg = "#e3c36c", bold = true }
tab_inactive = { fg = "#ffe08c", bg = "#241a00" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#7cd27f", bg = "#7cd27f" }
marker_cut = { fg = "#c8ecc9", bg = "#c8ecc9" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#adcfae", bg = "#adcfae" }

# Count
count_copied = { fg = "#03210b", bg = "#c8ecc9" }
count_cut = { fg = "#03210b", bg = "#c8ecc9" }
count_selected = { fg = "#3d2f00", bg = "#adcfae" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#e3c36c" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#3d2f00", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#e3c36c", fg = "#3d2f00", bold = true }
normal_alt  = { bg = "#4c4639", fg = "#cfc5b4" }

# Select mode
select_main = { bg = "#d5c5a1", fg = "#392f15", bold = true }
select_alt  = { bg = "#4c4639", fg = "#cfc5b4" }

# Unset mode
unset_main = { bg = "#adcfae", fg = "#19361f", bold = true }
unset_alt  = { bg = "#4c4639", fg = "#cfc5b4" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#e3c36c", bg = "#3d392f" }
progress_error = { fg = "#ffb4ab", bg = "#3d392f" }

# Permissions
permissions_t = { fg = "#997f44" }
permissions_w = { fg = "#548f56" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#56c559" }
permissions_s = { fg = "#f2b100" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#e3c36c" }
active = { fg = "#adcfae", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#e3c36c" }
value = { fg = "#eae1d4" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#e3c36c", bg = "#3d2f00" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#e3c36c" }
title = {}
hovered = { fg = "#c8ecc9", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3d392f" }
cand = { fg = "#e3c36c" }
rest = { fg = "#3d2f00" }
desc = { fg = "#eae1d4" }
separator = " ‚ñ∂ "
separator_style = { fg = "#eae1d4" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#eae1d4" }
run = { fg = "#eae1d4" }
footer = { fg = "#392f15", bg = "#d5c5a1" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#adcfae" }
title_warn = { fg = "#e3c36c" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#eae1d4" },
    { name = "*/", fg = "#e3c36c" },
]

# : ]]]